# This workflow is triggered manually before release

name: Snapshot Checks

on: workflow_dispatch

jobs:
  snapshot-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Assemble projects
        run: ./gradlew -PsnapshotTesting=true assembleDebugAndroidTest
